language: R
cache: packages
sudo: false
branches:
  only:
  - master
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
before_script:
- chmod +x ./_render.sh
- chmod +x ./_push.sh
script: "./_render.sh && ./_push.sh"
env:
  global:
    secure: VU0n4rNIilBArbFHjc2ZXUNzzGka/rKdW81Jd8UxUtIB/RqyWR0lqnaDdrq5dlUyXwVrAkIE3CAHJEUufFPAoRYuRDwWY0EXI79gERc0zPq90TbveNLXpB8xyjuUkN4hv4dZ0d7UY+WYLPj/Gkid1nFYt7qwCa6oe60d3bN12EFYwhEPKlzN/7wM7kgDLxGfpGDspiZGatI/D7lO02AWlc72d8NBQxA4X+6jQtJZBhVh2QNZfTmTRPoL636AJkRPoJTyLNvRZVR4zWdpp1J54frFeky+blvNnFEEzOnmz6ZV+5g5DovRVpTLdUb4csPC6aqta1m5jBglU+iDo4J6g0fGKlmtj8AN7/AJF57crIGDtxK4UiYW0J/YaskwqHmT8UCUaaz6gO+5t7ggGp4bGKnKnQk5/NXEYU6PsRIflxajYYyvJgXCXi6mVZMFF7Vte+Lpmb7BLU4Gf4AgaZ98vDkBjBZAlt9iVGWLcYeIhXYqTpZMsg7pS/RmjeBYBiI+g/HRZWGlr+dSOu5Ntct4hiLdeXJRtc6Uhu+32pjNeXmVIc+xFS/g8dspgA+aNRnn3kVnlafRNHzbC6ltgmgkB9otrt6JdRIexBW0TiLlPrH4iIUs4Gi3uhnv68W3yTYG/MclwNO3IQx7qqN8yYetZc8GoN8mOWQ0ymOx11/gJ7s=
