language: R
cache: packages
sudo: false
branches:
  only:
  - master
repos:
  CRAN: https://cloud.r-project.org
  ropensci: http://packages.ropensci.org
r_github_packages:
- karthik/wesanderson
- hadley/scales
- hadley/ggplot2
- hadley/emo
before_script:
- chmod +x ./_render.sh
- chmod +x ./_push.sh
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
script: ./_render.sh && ./_push.sh
env:
  global:
    secure: 0k8iu5CgQkZ7bMr553E6I+bK32BeQk7q1WuXBMPExIUgqOvzHHrYSU2UAqsCuS0kKskatvrFFwASWRQajWMFIOLmyXUaQ0sd9fN2R1ysFeD6z9gPxKNYPiAn4/q0zFBKZqQZ6oZK7xWhC/5xXwQzAItE8qDlzMQ5qosGJdr75pHBIQuEWJYwC9tz5doD7CQawpSly0KwFZ1UPKdbhGN1JBk0X1DoP7AcIr+I+Uov7fesYTc//2iy0JtXhBxehoGIJdFJFoOLIWyLWQActlRD88cHXCAk0Im67DguK/UYFTMUUP+cWPrklaPRQi/BPs5E295ucxJvrMXw5BY2SWGKkG4Z+MqXIuXoi9uro7J0NXtHUJ83fDM2z63dPUH/pYtTojlbHZ07fk+y8n03Z4cF8+m5z/KtvIYsUUB2AeRtfE6uPvXjK4AeUAuEfZDPnDteyQrOoDFnXWi2/ubUlr4rppWLKuGd01eHVzKDJm4BqdkjMTIMaYkDGvw8xWHqsKO1BHULR+HbhDH+FDubMLizfiJUEwYPPdQTEc0oanC5RlYK+XmlQyVJPbv8CJBY/G4HTZpjA294F3WvZy5jJmZlEXjmi27o9bGQsECFAt8uI2bv2RzL7bLnToStbYA54jUHUlTnVpnyWrm1mIIlej7KsBd3hjiXnSQ+iAEFafjPz0w=
